/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.eagerlogic.viwib.launcher;

import java.awt.EventQueue;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author dipacs
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        try {
            this.setIconImage(ImageIO.read(this.getClass().getResourceAsStream("/com/eagerlogic/viwib/launcher/logo_64.png")));
        } catch (IOException ex) {
            Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void setStatus(final String text) {
        EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                lblState.setText(text);
            }
        });
    }
    
    public String getStatus() {
        return this.lblState.getText();
    }
    
    public void setProgress(final int progress) {
        EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                pbProgress.setValue(progress);
            }
        });
    }
    
    public int getProgress() {
        return pbProgress.getValue();
    }
    
    public void setBackgroundImage(final String imageUrl) {
        EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                InputStream is = null;
                try {
                    try {
                        lblBackground.setIcon(new ImageIcon(ImageIO.read(new File(imageUrl))));
                    } catch (IOException ex) {
                        Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } finally {
                    if (is != null) {
                        try {
                            is.close();
                        } catch (IOException ex) {
                            Logger.getLogger(SplashScreen.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblState = new javax.swing.JLabel();
        pbProgress = new javax.swing.JProgressBar();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        lblState.setForeground(new java.awt.Color(255, 255, 255));
        lblState.setText("Checking updates...");
        lblState.setBounds(10, 260, 530, 14);
        jLayeredPane1.add(lblState, javax.swing.JLayeredPane.DEFAULT_LAYER);

        pbProgress.setForeground(new java.awt.Color(64, 192, 255));
        pbProgress.setBorderPainted(false);
        pbProgress.setBounds(0, 280, 550, 10);
        jLayeredPane1.add(pbProgress, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/eagerlogic/viwib/launcher/splash.png"))); // NOI18N
        lblBackground.setText("jLabel1");
        lblBackground.setBounds(0, 0, 550, 350);
        jLayeredPane1.add(lblBackground, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblState;
    private javax.swing.JProgressBar pbProgress;
    // End of variables declaration//GEN-END:variables
}
